url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "TWI Triple Win Initiative" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - package.json
  - pnpm-lock.yaml
  - postcss.config.js
