url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# https://github.com/triple-win-initiative/QuiCK-website/tree/main/content/
title: About Quick
description: Working alongside IPA Kenya and a local social enterprise, we are testing a pioneering approach to building a stronger childcare market from the ground up.
logo: "/assets/images/funder_logos/IPA.png"
plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  team: 
    output: true
    permalink: /team/:slug/
  blog: 
    output: true
    permalink: /blog/:slug/
  pages: 
    output: true
    permalink: /:slug/
exclude:
  - package.json
  - pnpm-lock.yaml
  - postcss.config.js
