url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "TWI Triple Win Initiative" # the name of your site, e.g. ACME Corp.
# https://github.com/triple-win-initiative/QuiCK-website/tree/main/content/
plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  team: 
    output: true
    permalink: /team/:slug/
  blog: 
    output: true
    permalink: /blog/:slug/
  pages: 
    output: true
    permalink: /:slug/
exclude:
  - package.json
  - pnpm-lock.yaml
  - postcss.config.js
