url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# https://github.com/triple-win-initiative/QuiCK-website/tree/main/content/
title: About Quick
description: Working alongside IPA Kenya and a local social enterprise, we are testing a pioneering approach to building a stronger childcare market from the ground up.
logo: "/assets/images/funder_logos/IPA.png"
plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  # https://github.com/toshimaru/jekyll-toc
picture: 
  ignore_missing_images: true
jekyll_picture_tag:
  source: /_images
  output: generated
  defaults:
    copy_original: false
    alt: illustration
  media_queries:
      mobile: 'max-width: 480px'
      tablet: 'max-width: 768'
      laptop: 'max-width: 1024px'
      desktop: 'max-width: 1200'
      wide: 'min-width: 1920'
  format_quality:
      jpg: 70
      png: 70
      webp: 60

collections:
  team: 
    output: true
    permalink: /team/:slug/
  posts: 
    output: true
    permalink: /blog/:title/
  pages: 
    output: true
    permalink: /:slug/
exclude:
  - package.json
  - pnpm-lock.yaml
  - postcss.config.js
  - README.md
  - LICENSE
  - yarn.lock
  - tailwind.config.js
